[phases.setup]
aptPkgs = [
  "python3-pip",
  "tesseract-ocr",
  "tesseract-ocr-eng",
  "tesseract-ocr-tur"
]

[phases.install]
cmds = ["/usr/bin/python3 -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "/usr/bin/python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT"
